version: '3.9'
services:
  web:
    image: tubes-1:latest
    container_name: php8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    env_file: .env
    networks:
      - web-postgres
  db:
    image: postgres
    container_name: pg_data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./muse_app_backup.sql:/muse_app_backup.sql
    networks:
      - web-postgres
networks:
  web-postgres:
    driver: bridge